apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    {{ .Files.Get "files/grafana/grafana.ini" | indent 4 }}
  
  ldap.toml: |
    {{ .Files.Get "files/grafana/ldap.toml" | indent 4 }}
