---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-plugins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logstash.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-lib-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logstash.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logstash.persistence.size }}

